# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'G-XJSGZSVTR3'

menu:
- {name: 'Products',          url: 'products'}
- {name: 'Docs',               url: 'docs'}
- {name: 'Careers',           url: 'https://www.linkedin.com/company/muddyterrain/jobs/'}
- {name: 'Support',           url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'x-twitter', link:    'https://x.com/muddyterrain'}
- {icon: 'instagram', link:  'https://instagram.com/muddyterrain'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/company/muddyterrain/'} 
- {icon: 'github',    link: 'https://github.com/muddyterrain'}
- {icon: 'envelope', link:   'mailto:mail@muddyterrain.com'}
- {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'discord', link: '/t/discord'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'

# Example Project Downloads
example_projects:
  - version: "5.7"
    cpp_link: "https://drive.google.com/file/d/1D_qXIuXMili_BGDxgfkCtbl2OxwZ1tkA/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1T9TlhvYWjBtoFcuANE1SAkBPY6gj-lS-/view?usp=drive_link"
  - version: "5.6"
    cpp_link: "https://drive.google.com/file/d/1t04JAFKbtdSe4spBVg8SIM6an2e6-O4X/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1ALI9sEG-ucdbzXqWyEFzMkddobnaDQ6Z/view?usp=drive_link"
  - version: "5.5"
    cpp_link: "https://drive.google.com/file/d/1_EHEUgvRw-1B4RTNcwTqGb7E2GQ55y2e/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1SkVp9lkMHDDW2ZXfm8MEfrob1FAPxBIz/view?usp=drive_link"
  - version: "5.4"
    cpp_link: "https://drive.google.com/file/d/18U04OcGSWT14pctANdLVfjWZrZ71yFiT/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1ylRhqa42J9mvq03VhP-GyIzSojnRdqlP/view?usp=drive_link"
  - version: "5.3"
    cpp_link: "https://drive.google.com/file/d/1UBnGA5pxCU_yS1RzE8Q6nUbbn2fWG9lP/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1_xbvQWuIqqGWNsqNT-PbVzetnmkzGVsO/view?usp=drive_link"
  - version: "5.2"
    cpp_link: "https://drive.google.com/file/d/1ZIBSpW3eVin3S98SqZMp_rZdaArV3uM-/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1Q05HxHW0lA9U6lb1vOIkPwHG2Iw3c75_/view?usp=drive_link"
  - version: "5.1"
    cpp_link: "https://drive.google.com/file/d/1edLQnohr0wMcPqdN41-a56zFe_TUwtNv/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1YTpOhFUSn1fNlA0YP-WOV0h6YXwR0H2_/view?usp=drive_link"

# Gen AI China Example Project Downloads
example_projects_china:
  - version: "5.7"
    bp_link: "https://drive.google.com/file/d/1-4YhcTu-RIi0fCmoYksmukVGupqJr4dE/view?usp=drive_link"
  - version: "5.6"
    bp_link: "https://drive.google.com/file/d/1hezveggvk8Z8qDaPlJwImfhefuw505EV/view?usp=drive_link"
  - version: "5.5"
    bp_link: "https://drive.google.com/file/d/1DJHyjtCLFS3EBeCq7sMGD0IRqc5YbLdV/view?usp=drive_link"
  - version: "5.4"
    bp_link: "https://drive.google.com/file/d/1vzKaMqhlb86Owp2VTQpBFFDs3ytq3xc4/view?usp=drive_link"
  - version: "5.3"
    bp_link: "https://drive.google.com/file/d/1ri7O9RwmsfCJg4viDUiw-D_Of0wfisXH/view?usp=drive_link"
  - version: "5.2"
    bp_link: "https://drive.google.com/file/d/1bXoRjH4BmEahHrXSEA75WtU6DWpQ9FSV/view?usp=drive_link"
  - version: "5.1"
    bp_link: "https://drive.google.com/file/d/1bXoRjH4BmEahHrXSEA75WtU6DWpQ9FSV/view?usp=drive_link"

# GenAI Llama Example Project Downloads
example_projects_llama:
  - version: "5.7"
    bp_link: "https://drive.google.com/file/d/18nMwVU_6-FZon6VJUtrRUkbDmG7jVNjs/view?usp=drive_link"
  - version: "5.6"
    bp_link: "https://drive.google.com/file/d/1MRDpySnJUesllA58H8lxo6k6KAkIfpPT/view?usp=drive_link"
  - version: "5.5"
    bp_link: "https://drive.google.com/file/d/1qqkg8M-jAOGbW-p2bG2AsReRJHuPiG8Z/view?usp=drive_link"
  - version: "5.4"
    bp_link: "https://drive.google.com/file/d/1kzWFolblKAD5YeE9IO4w9aYSUPJyRZnQ/view?usp=drive_link"
  - version: "5.3"
    bp_link: "https://drive.google.com/file/d/1b2b7kMEHaRntn0DHffzl9PsBePH9wUNK/view?usp=drive_link"
  - version: "5.2"
    bp_link: "https://drive.google.com/file/d/1uArW0C5MdLv47aUilEBEKN2wLfC6Yuwd/view?usp=drive_link"
  - version: "5.1"
    bp_link: "https://drive.google.com/file/d/1Eu7B6nENl_HkmAK60V9uhflSel6ifG0p/view?usp=drive_link"

# GenAI Model Generator Example Project Downloads
example_projects_modelgenerator:
  - version: "5.7"
    bp_link: "https://drive.google.com/file/d/1CZgEoRg7U0G4QkwqDuyMpM6OGGsSCNEB/view?usp=drive_link"
  - version: "5.6"
    bp_link: "https://drive.google.com/file/d/1TRwW9obpHMutyjeJ6ojBSZNZ2DxKIzXv/view?usp=drive_link"
  - version: "5.5"
    bp_link: "https://drive.google.com/file/d/1KBH5nDnnXH4K5KH6Ej8UppSQf-W50Otj/view?usp=drive_link"
  - version: "5.4"
    bp_link: "https://drive.google.com/file/d/1DsS_8nXwQC8jtju1CFfjMyx81ssxwIhH/view?usp=drive_link"
  - version: "5.3"
    bp_link: "https://drive.google.com/file/d/12tbij0tlBuvOfbjSdxug6yitrgc6U3CP/view?usp=drive_link"
  - version: "5.2"
    bp_link: "https://drive.google.com/file/d/1CNHIiY8JHaO70h7okiJklH5LyxtGXjTp/view?usp=drive_link"
  - version: "5.1"
    bp_link: "https://drive.google.com/file/d/19v9ND0uaSfr_PT2MzgwRAIcJRcMlKioc/view?usp=drive_link"
